book/urls.py
from django.urls import path
from . import views


app_name = 'book'
urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('book/new/', views.book_new, name='book_new'),
    path('book/<int:pk>/edit/', views.book_edit, name='book_edit'),
    path('book/<int:pk>/delete/', views.book_delete, name='book_delete'),
]

bookapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book/models.py
from django.db import models


class Book(models.Model):
    LIBRARY_CHOICES = (
        ('国立図書館', '国立図書館'),
        ('県立図書館', '県立図書館'),
        ('市立図書館', '市立図書館'),
    )
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    holder = models.CharField(
        max_length=10,
        choices=LIBRARY_CHOICES,
    )
    user = models.CharField(max_length=50)
    published_date = models.DateField(
        blank=True, null=True)
    purchased_date = models.DateField(
        blank=True, null=True)
    isbn = models.BigIntegerField()
    comment = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

book/forms.py
from django import forms
# from .models import Book


# class BookForm(forms.ModelForm):
#     class Meta:
#         model = Book
#         fields = ('isbn', 'comment',)

LIBRARIES_CHOICES = (
    ('国立図書館', '国立図書館'),
    ('県立図書館', '県立図書館'),
    ('市立図書館', '市立図書館'),
)


class BooksForm(forms.Form):
    title = forms.CharField(
        label='タイトル',
        max_length=200,
        required=True,
    )

    author = forms.CharField(
        label='著者',
        max_length=50,
        required=True,
    )

    holder = forms.ChoiceField(
        label='所有者',
        widget=forms.Select,
        choices=LIBRARIES_CHOICES,
        required=True,
    )

    user = forms.CharField(
        label='貸出先',
        max_length=50,
        required=True,
    )

    published_date = forms.DateTimeField(
        label='発刊日',
        required=True,
        widget=forms.DateInput(attrs={"type": "date"}),
        input_formats=['%Y-%m-%d']
    )

    purchased_date = forms.DateTimeField(
        label='購入日',
        required=True,
        widget=forms.DateInput(attrs={"type": "date"}),
        input_formats=['%Y-%m-%d']
    )

    isbn = forms.IntegerField(
        label='isbn',
        required=False,
    )

    comment = forms.CharField(
        label='備考',
        max_length=1000,
        required=False,
        widget=forms.TextInput()
    )

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Book
from .forms import BooksForm


def book_list(request):
    books = Book.objects.all().order_by('published_date')
    return render(request, 'book/book_list.html', {'books': books})


def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'book/book_detail.html', {'book': book})


# def book_new(request):
#     if request.method == "POST":
#         form = BooksForm(request.POST)
#         if form.is_valid():
#             book = form.save()
#             book.save()
#             return redirect('book:book_detail', pk=book.pk)
#
#     else:
#         form = BooksForm()
#     return render(request, 'book/book_new.html', {'form': form})

def book_new(request):
    form = BooksForm(request.POST or None)
    if form.is_valid():
        book = Book()
        book.title = form.cleaned_data['title']
        book.author = form.cleaned_data['author']
        book.holder = form.cleaned_data['holder']
        book.user = form.cleaned_data['user']
        book.published_date = form.cleaned_data['published_date']
        book.purchased_date = form.cleaned_data['purchased_date']
        book.isbn = form.cleaned_data['isbn']
        book.comment = form.cleaned_data['comment']

        Book.objects.create(
            title=book.title,
            author=book.author,
            holder=book.holder,
            user=book.user,
            published_date=book.published_date,
            purchased_date=book.purchased_date,
            isbn=book.isbn,
            comment=book.comment,
        )
        return redirect('book:book_list')
    return render(request, 'book/book_new.html', {'form': form})


# def book_edit(request, pk):
#     book = get_object_or_404(Book, pk=pk)
#     if request.method == "POST":
#         form = BooksForm(request.POST, instance=book)
#         if form.is_valid():
#             book = form.save()
#             book.save()
#             return redirect('book:book_detail', pk=book.pk)
#     else:
#         form = BooksForm(instance=book)
#     return render(request, 'book/book_edit.html', {'form': form, 'pk': pk})

def book_edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = BooksForm(request.POST)
        if form.is_valid():
            book = Book()
            book.title = form.cleaned_data['title']
            book.author = form.cleaned_data['author']
            book.holder = form.cleaned_data['holder']
            book.user = form.cleaned_data['user']
            book.published_date = form.cleaned_data['published_date']
            book.purchased_date = form.cleaned_data['purchased_date']
            book.isbn = form.cleaned_data['isbn']
            book.comment = form.cleaned_data['comment']

            Book.objects.filter(pk=pk).update(
                title=book.title,
                author=book.author,
                holder=book.holder,
                user=book.user,
                published_date=book.published_date,
                purchased_date=book.purchased_date,
                isbn=book.isbn,
                comment=book.comment,
            )
            book = get_object_or_404(Book, pk=pk)
            return render(request, 'book/book_detail.html', {
                'book': book,
                'pk': pk,
            })

    else:
        data = {
            'title': book.title,
            'author': book.author,
            'holder': book.holder,
            'user': book.user,
            'published_date': book.published_date,
            'purchased_date': book.purchased_date,
            'isbn': book.isbn,
            'comment': book.comment,
        }
        form = BooksForm(data)
    return render(request, 'book/book_edit.html', {
        'form': form,
        'pk': pk
    })


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        book.delete()
        return redirect('book:book_list')
    return render(request, 'book/book_confirm_delete.html', {'book': book})

book/templates/book/base.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/book.css' %}">
        <title>Django Libraries</title>
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'book:book_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="/">Django Libraries</a></h1>
        </div>
        <div class="content container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

book/templates/book/book_confirm_delete.html
{% extends 'book/base.html' %}

{% block content %}
    <h1>Book Delete</h1>
    <div class="book">
        <p>タイトル：{{ book.title }}</p>
        <p>著者：{{ book.author }}</p>
        <p>持ち主：{{ book.holder }}</p>
        <p>発刊日：{{ book.published_date }}</p>
    </div>

    <form method="post">
        {% csrf_token %}
        <p>本当に削除しますか ?</p>
        <a class="btn btn-primary" href="{% url 'book:book_detail' pk=book.pk %}" role="button">戻る</a>
        <button class="btn btn-danger" type="submit">削除</button>

    </form>
{% endblock %}

book/templates/book/book_detail.html
{% extends 'book/base.html' %}

{% block content %}
    <div class="book">
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'book:book_edit' pk=book.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-default" href="{% url 'book:book_delete' pk=book.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
        {% endif %}

        <h1>{{ book.title }}</h1>
        <p>著者：{{ book.author }}</p>
        <p>持ち主：{{ book.holder }}</p>
        <p>使用者：{{ book.user }}</p>
        <p>発刊日：{{ book.published_date }}</p>
        <p>購入日：{{ book.purchased_date }}</p>
        <p>ISBN：{{ book.isbn }}</p>
        <p>備考：{{ book.comment|linebreaksbr }}</p>
    </div>
{% endblock %}

book/templates/book/book_edit.html
{% extends 'book/base.html' %}

{% block content %}
    <h1>Edit book</h1>
    <table class="table">
    <form method="post" action="">
    {% csrf_token %}
    <tbody>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>著者</th>
        <td>{{ form.author }}</td>
      </tr>
      <tr>
        <th>所有者</th>
        <td>{{ form.holder }}</td>
      </tr>
      <tr>
        <th>貸出先</th>
        <td>{{ form.user }}</td>
      </tr>
      <tr>
        <th>発刊日</th>
        <td>{{ form.published_date }}</td>
      </tr>
      <tr>
        <th>購入日</th>
        <td>{{ form.purchased_date }}</td>
      </tr>
      <tr>
        <th>ISBN</th>
        <td>{{ form.isbn }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ form.comment }}</td>
      </tr>
    </tbody>
      <tr>
      <td><input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </td>
      </tr>
    </form>
  </table>
{% endblock %}

book/templates/book/book_list.html
{% extends 'book/base.html' %}

{% block content %}

    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">所有者</th>
          <th scope="col">貸出先</th>
          <th scope="col">発刊日</th>
          <th scope="col">購入日</th>
        </tr>
      </thead>
      <tbody>
    {% for book in books %}
        <tr>
          <td><a href="{% url 'book:book_detail' pk=book.pk %}">{{ book.title|truncatechars:30 }}</a></td>
          <td>{{ book.holder }}</td>
          <td>{{ book.user }}</td>
          <td>{{ book.published_date }}</td>
          <td>{{ book.purchased_date }}</td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

{% endblock %}

book/templates/book/book_new.html
{% extends 'book/base.html' %}

{% block content %}
    <h1>New book</h1>

  <table class="table">
    <form method="post" action="">
    {% csrf_token %}
    <tbody>
      <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
      </tr>
      <tr>
        <th>著者</th>
        <td>{{ form.author }}</td>
      </tr>
      <tr>
        <th>所有者</th>
        <td>{{ form.holder }}</td>
      </tr>
      <tr>
        <th>貸出先</th>
        <td>{{ form.user }}</td>
      </tr>
      <tr>
        <th>発刊日</th>
        <td>{{ form.published_date }}</td>
      </tr>
      <tr>
        <th>購入日</th>
        <td>{{ form.purchased_date }}</td>
      </tr>
      <tr>
        <th>ISBN</th>
        <td>{{ form.isbn }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ form.comment }}</td>
      </tr>
    </tbody>
      <tr>
      <td><input class="btn btn-primary" type="submit" value="Submit">
        <input class="btn btn-secondary" type="reset" value="Reset">
      </td>
      <td>
      </td>
      </tr>
    </form>
  </table>

{% endblock %}